name: tires
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  fpdart: ^1.1.1
  skeletonizer: ^2.1.0+1
  cached_network_image: ^3.4.1
  share_plus: ^11.0.0
  flutter_secure_storage: ^9.2.4
  logger: ^2.6.1
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  flutter_cache_manager: ^3.4.1
  google_fonts: ^6.3.0
  auto_route: ^10.1.0+1
  image_picker: ^1.1.2
  path: ^1.9.1
  path_provider: ^2.1.5
  mime: ^2.0.0
  http: ^1.4.0
  http_parser: ^4.1.2
  crypto: ^3.0.6
  flutter_native_splash: ^2.4.6
  intl: ^0.20.2
  screenshot: ^3.0.0
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  file_saver: ^0.3.1
  fl_chart: ^1.0.0
  bot_toast: ^4.1.3
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
  auto_route_generator: ^10.1.0
  build_runner: ^2.5.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: InstrumentSans
      fonts:
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans-BoldItalic.ttf
          style: italic
          weight: 700

    - family: InstrumentSansCondensed
      fonts:
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_Condensed-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_Condensed-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_Condensed-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_Condensed-BoldItalic.ttf
          style: italic
          weight: 700

    - family: InstrumentSansSemiCondensed
      fonts:
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_SemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_SemiCondensed-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_SemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_SemiCondensed-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_SemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_SemiCondensed-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_SemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Instrument_Sans/static/InstrumentSans_SemiCondensed-BoldItalic.ttf
          style: italic
          weight: 700

    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans/static/NotoSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/Noto_Sans/static/NotoSans-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Noto_Sans/static/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Noto_Sans/static/NotoSans-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Noto_Sans/static/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Noto_Sans/static/NotoSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Noto_Sans/static/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans/static/NotoSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Noto_Sans/static/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Noto_Sans/static/NotoSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Noto_Sans/static/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Noto_Sans/static/NotoSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Noto_Sans/static/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Noto_Sans/static/NotoSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Noto_Sans/static/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Noto_Sans/static/NotoSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Noto_Sans/static/NotoSans-Black.ttf
          weight: 900
        - asset: assets/fonts/Noto_Sans/static/NotoSans-BlackItalic.ttf
          style: italic
          weight: 900

    - family: NotoSansCondensed
      fonts:
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-Black.ttf
          weight: 900
        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-BlackItalic.ttf
          style: italic
          weight: 900

    - family: NotoSansExtraCondensed
      fonts:
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-Black.ttf
          weight: 900
        - asset: assets/fonts/Noto_Sans/static/NotoSans_ExtraCondensed-BlackItalic.ttf
          style: italic
          weight: 900

    - family: NotoSansSemiCondensed
      fonts:
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-Black.ttf
          weight: 900
        - asset: assets/fonts/Noto_Sans/static/NotoSans_SemiCondensed-BlackItalic.ttf
          style: italic
          weight: 900

    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Thin.ttf
          weight: 100
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
